### ISSUE TITLE
Break out ad headline from ad

### ISSUE THREAD

**Issue by davidfischer** [readthedocs/ethical-ad-server#152]
Currently, we allow some limited HTML formatting in our ads and I'd like to stop this and instead have a bolded headline followed by plain text. This would allow for easier validation and custom formatting by publishers. While we use a good HTML sanitizer, I think not allowing HTML at all is probably better for security.

This will involve:

- Migrating existing ads that use HTML to the new format
- Changing our database model to support a headline
- Possibly changing ad styles to support the new output

## Screenshot of existing

![Screen Shot 2020-07-01 at 11 57 56 AM](https://user-images.githubusercontent.com/185043/86281267-20e94800-bb92-11ea-8647-9f755c7b1a3c.png)

**Comment by ericholscher** [comment]
I think this is a good idea, and should make image & text ads closer together in concept 👍

**Comment by davidfischer** [comment]
Here's my plan here:

- All ads will have a body and headline. We should also maybe consider an optional CTA (thoughts?). The headline and CTA will be bolded in the output. The body, headline, and CTA will all be plain text with no HTML.
- For new ads being created, always use a form that breaks the fields out and doesn't use `ad.text`. Behind the scenes, `ad.text` will get constructed from the body, headline, and CTA. When editing existing ads, use the old form with just `ad.text`. On the model, `ad.body`, `ad.headline` will be null/empty in the latter case. The form will ensure the combined length of the body, headline, and CTA fit in the required space.
- The ad API response will have the fields broken out. We will attempt to calculate the headline, body, and CTA in a similar fashion to this: https://github.com/readthedocs/ethical-ad-server/blob/5cea748c12ed748a904ed3125adcd7c843031308/adserver/models.py#L944-L947
- I'm leaning toward not having any sort of data migration for old ads. They'll just slowly phase out.

## Example

For example, with the following ad:

```python
ad.headline = "My Company"
ad.body = "Our widgets are the best."
ad.cta = "Try free for 30 days!"
```

The resulting HTML for the ad would be:

```html
<strong>My Company</strong> Our widgets are the best. <strong>Try free for 30 days!</strong>
```
```

**Comment by ericholscher** [comment]
Yea, this is what I was imagining. The API response contains the broken out fields, but also the `text` field which just standardizes the HTML response from the fields for legacy providers.
