### ISSUE TITLE
Ad types and existing advertisers and advertisements

### ISSUE THREAD

**Issue by davidfischer** [readthedocs/ethical-ad-server#163]
## The problem

One problem we have is that we have hundreds of existing ads in our system and we want to make it easy for advertisers to apply an existing ad across our new fledgling ad network.

The way that our current system is structured is that when an ad is requested by a site on the network (or Read the Docs), the exact ad type is specified. So a site will explicitly request an image+text ad. This is great except that then advertisers need to create 2 versions of the same ad: one with an image and one without even though they're basically the same. The other problem is that we have a separate ad type for ad network image+text ads from RTD image+text ads so an advertiser would need 2 versions of exactly the same ad (image+text for RTD, image+text for network) and then a 3rd version that is text-only. Long story short, for an existing advertiser to just show ads across our network, we need to duplicate their ads which is not desirable.

## Background

To give a bit of background, almost all of the ads in our existing system have an ad type that is Read the Docs specific. There are 3 RTD ad types:

* Sidebar ads: 80 characters + 240*180 image
* Footer ads: 300 characters + 240*180 image
* Fixed footer ads: 80 characters, no image

The 300 character footer ad type is deprecated and there are only a few of them but it is used on RTD. I don't think we ever want to use this across our ad network. Most of the publishers on our network want either a simple ad with an image or just a text ad. These two types are analogous to the Sidebar ad and the Fixed Footer ad on Read the Docs.

## Solutions

These are a couple different options. They are similar but we only need to do one of them.

### Move display logic into the ad client

Publishers will continue to express a preference for a text-only or text+image ad. However, the ad server would need a modification to send down the components of the ad like the text and the image and the client could assemble the HTML based on the publisher preference. In this case, the ad type on the ad server would be the same regardless of whether the ad is displayed with an image or without.

With respect to our existing ad types, I would suggest:

* Change the name of the sidebar ad to something like "Text and optional Image". Combine the RTD sidebar ad type and the "Ad network generic image v1" type. This ad type will be displayable either at text+image or text-only based on the publisher preference. On RTD, this will continue to be displayed only in the sidebar.
* Remove the "Ad network generic text" ad type. Whether to display an image+text or text-only will be by the publisher preference.
* The fixed footer type and the footer ad types will be RTD specific and not used elsewhere. They will continue to exist and simply be marked deprecated (the 300 character footer ad already is)

### Ad server accounts for the preference in addition to/instead of ad type

This is similar in that publishers will continue to express a preference for text-only or text+image ads. However, the request will not be specified as an ad type but instead as a display preference. We would need to pass an extra parameter -- the display preference -- to the logic that renders the ad to HTML on the server. The ad template could render with an image or without based on this preference. The ad server would continue to send down HTML of either a text-only or text+image ad based on this preference. The ad server would continue to accept the ad type but only RTD would send it to request either of the footer ad types. Other publishers would just send a preference.

We would probably change/modify our ad types the same as in the option above. The main text+image ad type would need some additional template logic to render with an image when that's the publisher preference or without.

### Ad types become many to many with ads

Edit: this was added after the initial issue

From a data modeling perspective, we could make ads a many-to-many (M2M) with ad types. An ad could have multiple types. The client would request a specific ad type (eg. text+image or text-only) and the server would find an ad of that type. Advertisers would specify that their ad applies to multiple types. A specific ad type still has a template for how it is rendered so the server would know how to render the ad based on the request. This would allow advertisers to opt-out of text-only ads but I think we could strongly discourage that -- by making it default to on -- without it being outright impossible.

With respect to our existing ad types, I would suggest:

* Change Advertisement.AdType to be M2M
* Add a field to AdType to say whether it should default to checked. Set this on the RTD sidebar, text-only, and text+image ad types.
* Consider merging the text+image ad type and the RTD sidebar ad type.

**Comment by agjohnson** [comment]
I'm not against moving this to the client. It would make versioning of templates less painful. However, DOM node creation without jquery is more tedious.

Alternatively, this seems related to the discussion about using an m2m field on Advertisements. If there was an m2m relation on Advertisement<->AdType only one advertisement would need to be created in most cases. This would preserve function of the existing AdType models and ad type templates.

Are we planning on continuing to use AdType model, and specifically it's templates? If so, there is benefit in everything working the same way.

On the customer side, do we need to add ad preference regardless of our display method? It seems advertisers might be adverse to text only ads and would want some control over whether their flight is image or image+text.

**Comment by davidfischer** [comment]
> If there was an m2m relation on Advertisement<->AdType only one advertisement would need to be created in most cases.

This solves only part of the problem. Either:

* The ad server needs to know the publisher's preference and output the ad as text-only if that's the preference even if the ad supports both text-only and text+image
* OR the client needs to handle that preference.

Our data modeling of the ad type might be part of one of the solutions but at some point either the client or server needs to handle outputting the correct format.

> Are we planning on continuing to use AdType model, and specifically it's templates?

I think we're definitely using the model. Whether we use its templates depends on whether we move display to the client.

> On the customer side, do we need to add ad preference regardless of our display method? It seems advertisers might be adverse to text only ads and would want some control over whether their flight is image or image+text.

I'm leaning toward no at least across the network. I want one ad that can be displayed in multiple ways. CodeFund, to my understanding, did not allow advertisers to opt-out of their ad being displayed without an image.

**Comment by ericholscher** [comment]
> I'm leaning toward no at least across the network. I want one ad that can be displayed in multiple ways. CodeFund, to my understanding, did not allow advertisers to opt-out of their ad being displayed without an image.

I think this is the correct call. I've already had a number of questions from publishers about how image vs text ads will change their payment or fill rate. I think if we can just run the same ads across the whole network, that will vastly simplify things to start with. We can always change this later, but lets start with the simple thing.

I don't feel like this really needs client changes. We can just map the `ad_type` of `image-v1`/`readthedocs-sidebar` and  or `text-v1`/`readthedocs-fixed-footer` to the same return values that we already have? Then we just change the ad filtering for a query from a type to just filter by `image=null`.

**Comment by davidfischer** [comment]
OK, I'm leaning toward option 3: making ad type many-to-many. This means no client changes and the ad server will handle things. A single ad can be displayed in multiple ways.
