### ISSUE TITLE
Validate ad landing page gives a 200

### ISSUE THREAD

**Issue by davidfischer** [readthedocs/ethical-ad-server#175]
We should validate that an ad landing page (`Advertisement.link`) gives a 200 or redirects to a 200. I'm not sure whether this should be a form error or just a warning after saving. However, I've seen advertisers make this mistake -- I check them -- and I think the system should catch it.

**Comment by ericholscher** [comment]
Yea, I think the URL validation in Django can be configured to do this.

**Comment by davidfischer** [comment]
I got another report of an advertiser with an issue related to this (a redirect). I think we should just raise a warning if the landing page returns a non-200.
