### ISSUE TITLE
Api to show publisher revenue

### ISSUE THREAD

**Issue by QuixThe2nd** [readthedocs/ethical-ad-server#297]
It would be awesome if it were possible to get details about revenue made from ad placements. I'd like an API where I can check how much I've made from certain placements. For example I could send a GET request to example.com/api/placement_info?id=test. Then every request to that uri would return how much I have made from the ads with the placement ID "test".

**Comment by davidfischer** [comment]
This may not give you exactly what you need but there is a general [publisher revenue report](https://ethical-ad-server.readthedocs.io/en/latest/user-guide/api.html#get--api-v1-publishers-(str-slug)-report-) that shows most of the same data that the UI shows. It would be at:

    https://server.ethicalads.io/api/v1/publishers/<publisher-slug>/report/

**Comment by QuixThe2nd** [comment]
What headers/post data do you have to attach for that to work?

**Comment by davidfischer** [comment]
I'm going to close this because I think we're good here.
