### ISSUE TITLE
Send URL with the ad request

### ISSUE THREAD

**Issue by davidfischer** [readthedocs/ethical-ad-server#354]
The URL where the ad is going to be displayed is useful for a few different reasons:

- We are considering building some functionality to process URLs after the fact to learn about what the content of those pages is about so we can have better contextual targeting
- Fraud detection
- Previously, we relied on the referrer which can't be trusted and quite a few of our publishers have a referrer policy that doesn't send it.

The main gotcha with collecting the URL is that we don't want to send any sensitive information in the URL like tokens. Maybe we just won't send query parameters? That won't be perfect on some sites but might be OK most of the time. Maybe we could have a blocklist of specific query parameters but that isn't ideal.

**Comment by ericholscher** [comment]
I'm 👍  on this. It would also be useful for helping understand a publishers traffic and where it's coming from. Currently we're depending on placements, but if we have more URL-specific data it could help on the backend for a few other reporting views at some point. 

I think a blocklist of URL params is probably a good start (eg. `session`). We might still end up with a username or similar in the URL, but that's already an issue with referral data as well. 

> The Referer header may not contain URL fragments (i.e. "#section") or "username:password" information. It can potentially contain an origin, path, and querystring. What is sent, if anything, depends on the referrer policy for the request. See Referrer-Policy for information and examples.

I think we can probably use [similar logic](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer), so it works in the same fashion.
