### ISSUE TITLE
No results from decision API despite valid(?) configuration

### ISSUE THREAD

**Issue by decaffeinatedio** [readthedocs/ethical-ad-server#432]
Hi!

I am now running EAS in a production environment, but for ease of reproduction all of my steps will refer to a local build. 

**Problem**
Even though I believe I have valid advertiser/publisher configurations, calls to the `/api/v1/decision/` endpoint do not return any ads results (nor does the tag-based call). 

**Steps to Reproduce - Build**
1. `git clone` the main repo or otherwise reference an unmodified version of the source code. 
2. `cd` into the repo and run `make dockerbuild`. 
3. `make dockershell` and run `./migrate.py migrate` then `./migrate.py createsuperuser`. 
4. Finally, run `make dockerserve` and log in with your superuser credentials at `localhost:5000`. 

**Steps to Reproduce - Running**
1. Create a new publisher; ensure that you enable all campaign types (e.g. paid) in the Admin panel. 
2. Create a new text ad type to keep things simple. 
3. Create a new advertiser, flight and ad, referencing your previously-created text ad type. 
4. With resources successfully created, set to live within the current date period and with any targeting removed (or inclusive of your ad request), call `'http://localhost:5000/api/v1/decision/?publisher=<PUBSLUGNAME>&div_ids=1&ad_types=text'`

In this final step, I get an empty object -- `{}` with a 200 OK.

Anything I may have missed to get back an ad response from the decision API? Thanks for any help!

**Comment by davidfischer** [comment]
This can be a few things:
* flight hasn't started yet or isn't live
* The publisher isn't approved for paid ads
* There's a targeting mismatch (although you addressed that)
* There isn't a valid text ad (it's image only or something) or the ad isn't live
* The ad type doesn't match (based on what you sent, it needs a slug `text`)

After checking all those, I'd step through [this](https://github.com/readthedocs/ethical-ad-server/blob/dca94ec2819b701d8ae2c7ad82be5d199eb9ef24/adserver/decisionengine/backends.py#L306-L312) in a debugger.

**Comment by decaffeinatedio** [comment]
> The ad type doesn't match (based on what you sent, it needs a slug text)

I believed that the `ad_types` param only had two generic enums -- `text` and `image` and that any ad type created on the server would be mapped to one of these two. Thanks for the guidance @davidfischer !

(BTW, I should have some small PRs for tweaks and maybe a working reference for running on Heroku soon).

**Comment by davidfischer** [comment]
> (BTW, I should have some small PRs for tweaks and maybe a working reference for running on Heroku soon).

Sounds good. I look forward to it. We did originally test this on Heroku but even with a comparable setup we got significantly better performance on Azure. Depending on your load, it may not matter though. We wrote about it here: https://www.ethicalads.io/blog/2021/07/handling-100-requests-per-second-with-python-django/
