### ISSUE TITLE
Docker container size and ML requirements

### ISSUE THREAD

**Issue by mattishaden** [readthedocs/ethical-ad-server#692]
I know that the Dockerfiles are not maintained, but just checking in here for some pointers. When building the containers, it becomes very big (6,8 GB) because of the pip requirements for the keyword/topic analyzer. I saw the ML stuff were moved out to a external repository, are the corresponding packages still needed in `requirements/`?

We're using a modified Dockerfile, but testing with `/local/django/Dockerfile` produces the same issue, while `/production/django/Dockerfile` results in build error.

**Comment by ericholscher** [comment]
@mattishaden Thanks for the issue. I'm curious what you're doing with the ad server? 

We aren't deploying via Docker at this point, so I'm not 100% sure the best way to run this in production. We're running directly on a machine, but it does take a good bit of memory & CPU to process the modeling. 

@davidfischer can probably chime in to answer the requirements question as well, but we do still need that for running certain parts of our operations, but not sure about in this repo.

**Comment by davidfischer** [comment]
You can use the ad server without our ML model at all. It uses a built-in model by default. However, the built-in stuff still requires some requirements like textacy/spacy. If you disable the analyzer entirely (that isn't currently an option but I guess it could be), then none of that is required at all.

**Comment by mattishaden** [comment]
> @mattishaden Thanks for the issue. I'm curious what you're doing with the ad server?
> 
I can drop you an e-mail about this. [eric@ericholscher.com](mailto:eric@ericholscher.com) ?

We are currently trying to upgrade from v0.41.0. It runs fine except that the database keeps growing.. Separate issue, but related to the offers table.

> You can use the ad server without our ML model at all. It uses a built-in model by default. However, the built-in stuff still requires some requirements like textacy/spacy. If you disable the analyzer entirely (that isn't currently an option but I guess it could be), then none of that is required at all.

Disable the analyzer would be preferable to us (no real use case for us there), but just knowing which requirements are optional and not would help to slim down the container size.

**Comment by ericholscher** [comment]
@mattishaden Yep, that's a good email.

**Comment by mattishaden** [comment]
We've upgraded to v0.49.0, that's the version before the machine learning requirements start accumulating. Alpine Dockerfile seems to abandoned in 0.54.0.

What happened with [https://github.com/readthedocs/ethicalads-model](https://github.com/readthedocs/ethicalads-model) repository? Interested to know your thoughts about the ML model going forward.

From our perspective, making the ML model optional and using an external repository (that the ethical-ads-server could communicate with somehow) would solve the problems with building the Alpine image and also slim down the size as all ML requirements would be in a separate application.

**Comment by davidfischer** [comment]
> What happened with https://github.com/readthedocs/ethicalads-model repository? Interested to know your thoughts about the ML model going forward.

We actually privatized this model. While the model itself isn't anything too special, the hand classified training data contained links to a bunch of repositories and we didn't want to publicize how we were training it precisely (this could be used by people gaming the system).

I plan to spend some time this week working on the dockerfile and making all the analysis optional.

**Comment by davidfischer** [comment]
I spent a bit of time in #703 to make the analyzer and its dependencies optional. This gets the production built Dockerfile to 1.4GB. I think there's still a bit of work to be done there, but please give this Docker setup a try @mattishaden and see if this is closer to what you need.

**Comment by mattishaden** [comment]
We're testing this now in our staging environment, but at first glance it seems to be running fine.

**Comment by davidfischer** [comment]
With #703 merged, I plan to close this out. The size should be much more reasonable and the analyzer is optional.
