### ISSUE TITLE
Stats above graph on reports page has wrong eCPM

### ISSUE THREAD

**Issue by JasonBarnabe** [readthedocs/ethical-ad-server#842]
The eCPM in the stats above the graph on the report page appears to be incorrect. It's correct in the table below the graph. All other stats are identical in both places.

[Sample page](https://server.ethicalads.io/publisher/greasyfork/report/?start_date=2024-03-01&end_date=2024-03-06&campaign_type=)

**Comment by davidfischer** [comment]
Thanks for the report. That eCPM is the CPM on paid only. Seems awkward that they don't match so I'll see if we can fix that.

**Comment by davidfischer** [comment]
The graphs now show both paid and unpaid impressions. Since the graph isn't displayed when there's filtering on the impression type, the numbers should match and I checked for you that they do.
