### ISSUE TITLE
How configure the application

### ISSUE THREAD

**Issue by mithucste30** [readthedocs/ethical-ad-server#922]
I am getting this error when i visit the geo page

`
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'metabase_advertiser_dashboard'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [metabase_advertiser_dashboard] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7db79736e440>>, 'request': <WSGIRequest: GET '/advertiser/kahf/report/geos/'>, 'user': <SimpleLazyObject: <User: admin@example.com>>, 'perms': PermWrapper(<SimpleLazyObject: <User: admin@example.com>>), 'messages': <FallbackStorage: request=<WSGIRequest: GET '/advertiser/kahf/report/geos/'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'adserver_ethicalads_branding': False, 'adserver_privacy_policy': None, 'adserver_publisher_policy': None, 'adserver_version': '5.7.0', 'plausible_domain': 'server.ethicalads.io'}, {}, {'start_date': datetime.datetime(2024, 9, 4, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='UTC')), 'end_date': datetime.datetime(2024, 10, 31, 9, 40, 4, 423198, tzinfo=datetime.timezone.utc), 'campaign_type': '', 'region': '', 'region_list': <QuerySet [<Region: US & Canada>, <Region: Wider APAC>, <Region: Australia & New Zealand>, <Region: South Asia>, <Region: Latin America>, <Region: Africa>, <Region: Commonly excluded countries>, <Region: All countries>]>, 'topic': '', 'topic_list': <QuerySet [<Topic: Backend web development>, <Topic: Blockchain>, <Topic: Data science & machine learning>, <Topic: DevOps>, <Topic: Frontend web development>, <Topic: Game development>, <Topic: Other>, <Topic: Python development>, <Topic: Security & privacy>, <Topic: Technical writing>]>, 'limit': 20, 'advertiser': <Advertiser: Kahf>, 'metabase_advertiser_geos': 200}, {'block': <Block Node: body_content. Contents: [<TextNode: '\n  <nav class="navbar nav'>, <URLNode view_name=''dashboard-home'' args=[] kwargs={} as=None>, <TextNode: '">\n      <span class="tex'>, <django.templatetags.i18n.TranslateNode object at 0x7db7973d4d00>, <TextNode: '</span>\n      <span class'>, <Variable Node: request.user.email>, <TextNode: '</a>\n          <div class'>, <IfNode>, <TextNode: '\n\n            <a class="d'>, <URLNode view_name=''account'' args=[] kwargs={} as=None>, <TextNode: '">\n              <span cl'>, <django.templatetags.i18n.TranslateNode object at 0x7db7973d5210>, <TextNode: '</span>\n            </a>\n'>, <URLNode view_name=''api_token_list'' args=[] kwargs={} as=None>, <TextNode: '">\n              <span cl'>, <django.templatetags.i18n.TranslateNode object at 0x7db7973d5330>, <TextNode: '</span>\n            </a>\n'>, <URLNode view_name=''account_change_password'' args=[] kwargs={} as=None>, <TextNode: '">\n              <span cl'>, <django.templatetags.i18n.TranslateNode object at 0x7db7973d5450>, <TextNode: '</span>\n            </a>\n'>, <URLNode view_name=''support'' args=[] kwargs={} as=None>, <TextNode: '">\n              <span cl'>, <django.templatetags.i18n.TranslateNode object at 0x7db7973d5570>, <TextNode: '</span>\n            </a>\n'>, <URLNode view_name=''account_logout'' args=[] kwargs={} as=None>, <TextNode: '">\n              <span cl'>, <django.templatetags.i18n.TranslateNode object at 0x7db7973d5690>, <TextNode: '</span>\n            </a>\n'>, <Block Node: breadcrumbs. Contents: [<TextNode: '\n      <li class="breadcr'>, <URLNode view_name=''dashboard-home'' args=[] kwargs={} as=None>, <TextNode: '">Home</a>\n      </li>\n  '>]>, <TextNode: '\n  </ol>\n\n  <div>\n    <di'>, <IfNode>, <TextNode: '\n\n          '>, <IfNode>, <TextNode: '\n        </nav>\n        <'>, <IncludeNode: template=<FilterExpression "'includes/messages.html'">>, <TextNode: '\n          '>, <IncludeNode: template=<FilterExpression '"adserver/includes/publisher-notices.html"'>>, <TextNode: '\n\n          '>, <Block Node: content_container. Contents: []>, <TextNode: '\n        </main>\n      </'>, <django.template.defaulttags.NowNode object at 0x7db7973e0df0>, <TextNode: ' Read the Docs, Inc.</spa'>, <IfNode>, <TextNode: '\n        '>, <IfNode>, <TextNode: '\n        '>, <IfNode>, <TextNode: '\n      </ul>\n      <ul cl'>, <Variable Node: adserver_version>, <TextNode: '</a>\n        </li>\n      '>]>}, {'block': <Block Node: content_container. Contents: [<TextNode: '\n\n<h1>'>, <Block Node: heading. Contents: [<django.templatetags.i18n.TranslateNode object at 0x7db7973c2080>]>, <TextNode: '</h1>\n\n\n'>, <Block Node: filters. Contents: [<TextNode: '\n  <section class="mb-5">'>, <django.templatetags.i18n.TranslateNode object at 0x7db7973c2230>, <TextNode: '</label>\n            <inp'>, <Variable Node: start_date|date:"Y-m-d">, <TextNode: '" pattern="[0-9]{4}-[0-9]'>, <django.templatetags.i18n.TranslateNode object at 0x7db7973c23e0>, <TextNode: '</label>\n            <inp'>, <IfNode>, <TextNode: '" pattern="[0-9]{4}-[0-9]'>, <TextNode: '\n          '>, <IfNode>, <TextNode: '\n\n          '>, <Block Node: additional_filters. Contents: []>, <TextNode: '\n        </div>\n\n        '>, <django.templatetags.i18n.TranslateNode object at 0x7db7973c3010>, <TextNode: '</button>\n      </form>\n '>]>, <TextNode: '\n\n'>, <TextNode: '\n'>, <Block Node: explainer. Contents: []>, <TextNode: '\n\n'>, <TextNode: '\n'>, <Block Node: toc. Contents: []>, <TextNode: '\n\n\n'>, <TextNode: '\n'>, <Block Node: chart. Contents: []>, <TextNode: '\n\n\n'>, <TextNode: '\n'>, <Block Node: summary. Contents: []>, <TextNode: '\n\n\n'>, <TextNode: '\n'>, <Block Node: report. Contents: []>, <TextNode: '\n\n\n'>, <Block Node: report_extras. Contents: []>, <TextNode: '\n\n'>]>}, {'block': <Block Node: toc. Contents: [<TextNode: '\n  '>, <IfNode>, <TextNode: '\n'>]>}]
INFO     2024-10-04 09:40:04,773 [django.server] "GET /advertiser/kahf/report/geos/ HTTP/1.1" 200 9748
DEBUG    2024-10-04 09:40:05,416 [django.utils.autoreload] File /usr/lib/python3.10/_strptime.py first seen with mtime 1726069656.0
DEBUG    2024-10-04 09:40:05,417 [django.utils.autoreload] File /usr/local/lib/python3.10/dist-packages/django/contrib/messages/storage/fallback.py first seen with mtime 1727617289.0
DEBUG    2024-10-04 09:40:05,419 [django.utils.autoreload] File /app/config/context_processors.py first seen with mtime 1727589704.0
DEBUG    2024-10-04 09:40:05,422 [django.utils.autoreload] File /usr/local/lib/python3.10/dist-packages/django/contrib/sessions/serializers.py first seen with mtime 1727617289.0
DEBUG    2024-10-04 09:40:05,424 [django.utils.autoreload] File /usr/local/lib/python3.10/dist-packages/tzdata/__init__.py first seen with mtime 1727617284.0
DEBUG    2024-10-04 09:40:05,424 [django.utils.autoreload] File /usr/local/lib/python3.10/dist-packages/django/contrib/messages/context_processors.py first seen with mtime 1727617289.0
DEBUG    2024-10-04 09:40:05,425 [django.utils.autoreload] File /usr/local/lib/python3.10/dist-packages/django/contrib/messages/storage/session.py first seen with mtime 1727617289.0
DEBUG    2024-10-04 09:40:05,425 [django.utils.autoreload] File /usr/local/lib/python3.10/dist-packages/django/conf/locale/en/__init__.py first seen with mtime 1727617289.0
DEBUG    2024-10-04 09:40:05,426 [django.utils.autoreload] File /usr/local/lib/python3.10/dist-packages/django/template/context_processors.py first seen with mtime 1727617289.0
DEBUG    2024-10-04 09:40:05,433 [django.utils.autoreload] File /usr/local/lib/python3.10/dist-packages/django/conf/locale/en/formats.py first seen with mtime 1727617289.0
DEBUG    2024-10-04 09:40:05,433 [django.utils.autoreload] File /usr/local/lib/python3.10/dist-packages/tzdata/zoneinfo/__init__.py first seen with mtime 1727617284.0
DEBUG    2024-10-04 09:40:05,433 [django.utils.autoreload] File /usr/local/lib/python3.10/dist-packages/django/contrib/auth/context_processors.py first seen with mtime 1727617289.0
DEBUG    2024-10-04 09:40:05,434 [django.utils.autoreload] File /usr/local/lib/python3.10/dist-packages/django/contrib/messages/storage/cookie.py first seen with mtime 1727617289.0
DEBUG    2024-10-04 09:55:34,616 [django.template] Exception while resolving variable 'show_keyword_report' in template 'adserver/reports/advertiser-geo.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
TypeError: 'Advertiser' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'Advertiser' object has no attribute 'show_keyword_report'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'show_keyword_report'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [show_keyword_report] in <Advertiser: Kahf>
DEBUG    2024-10-04 09:55:34,618 [django.template] Exception while resolving variable 'show_topic_report' in template 'adserver/reports/advertiser-geo.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
TypeError: 'Advertiser' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'Advertiser' object has no attribute 'show_topic_report'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'show_topic_report'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [show_topic_report] in <Advertiser: Kahf>
DEBUG    2024-10-04 09:55:34,620 [django.template] Exception while resolving variable 'publisher' in template 'adserver/reports/advertiser-geo.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.10/dist-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'publisher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 881, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'publisher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'publisher'
`

**Comment by mithucste30** [comment]
Also I having hard time to understand how to configure metabase properly, currently my dashboard shows like this
<img width="1492" alt="Screenshot 2024-10-04 at 4 12 18 PM" src="https://github.com/user-attachments/assets/03dbfd12-95e3-4999-a269-60a389426d5f">

**Comment by mithucste30** [comment]
I am running the application inside docker-compose

```docker-compose
volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }
  local_metabase_db: { }
  local_metabase_data: { }
  local_media: { }

services:
  django:
    image: repo/ethical-adserver/backend:latest
    depends_on:
      - postgres
    command: /start
    volumes:
      - local_media:/app/media
    <<: *django-env

  postgres:
    image: repo/ethical-adserver/postgres:latest
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ethicaladserver
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpass

  redis:
    image: redis:5.0

  celery_worker:
    image: repo/ethical-adserver/backend:latest
    depends_on:
      - redis
      - postgres
    <<: *django-env
    command: /start-celeryworker

  celery_beat:
    image: repo/ethical-adserver/backend:latest
    depends_on:
      - redis
      - postgres
    <<: *django-env
    command: /start-celerybeat

  metabase:
    image: metabase/metabase
    volumes:
      - local_metabase_data:/metabase-data
    depends_on:
      - metabase_db
    environment:
      - MB_ENCRYPTION_SECRET_KEY=${METABASE_SECRET_KEY}
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase_app_db
      - MB_DB_PORT=5432
      - MB_DB_USER=localuser
      - MB_DB_PASS=localpass
      - MB_DB_HOST=metabase_db

  metabase_db:
    image: postgres:16.4-bullseye
    volumes:
      - local_metabase_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=metabase_app_db
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpass
```

**Comment by mithucste30** [comment]
I am also having hard time to understand how to load questions and dashboards inside metbase? Is there any script inside the project to do that?

**Comment by ericholscher** [comment]
We don't have the metabase dashboards anywhere OSS, so you'd need to recreate them somehow. I'd probably just disable them for now.
