### ISSUE TITLE
Unknown task

### ISSUE THREAD

**Issue by mithucste30** [readthedocs/ethical-ad-server#937]
I have set analyzer backend to `adserver.analyzer.backends.TextacyAnalyzerBackend`

But in the celery I am getting this error when running task

`KeyError: 'adserver.analyzer.tasks.daily_analyze_advertiser_urls'
  File "celery/worker/consumer/consumer.py", line 660, in on_task_received
    strategy = strategies[type_]`

**Comment by davidfischer** [comment]
This is definitely a bug and I will get it fixed up. It works in our production setup because we have some extra tasks (including this one) that are not open source.
