### ISSUE TITLE
Some countries show no stats

### ISSUE THREAD

**Issue by JasonBarnabe** [readthedocs/ethical-ad-server#959]
As a publisher, looking at the my Geo Report, I can see stats on a per-country basis. I can see all sorts of crazy countries have been presented ads - Vatican City, North Korea, Marshall Islands... And yet some big countries, like China, Russia, and Iran, show 0 views.

I understand that you may not have sold ads in these countries, and that there may even be legal reasons why you can't... But shouldn't they be showing X views and 0 fill rate?

This would make it easier for me to understand some discrepancies I'm seeing between what I'm recording in Google Analytics and what Ethical Ads's reports are showing me.

**Comment by davidfischer** [comment]
> I understand that you may not have sold ads in these countries, and that there may even be legal reasons why you can't... But shouldn't they be showing X views and 0 fill rate?

We generally don't sell ads there and we don't serve unpaid ads there either. They will show 0 views as a result.

> North Korea

They have now been added to the default block list.

> This would make it easier for me to understand some discrepancies I'm seeing between what I'm recording in Google Analytics and what Ethical Ads's reports are showing me.

These two things are not very comparable. We have an [FAQ](https://www.ethicalads.io/publishers/faq/#analytics-shows-more-pageviews-than-youre-showing-ad-views-why) on this specifically. There's a number of reasons for this, but the biggest is that we're counting different things. An ad has to be visible for a certain amount of time before it even registers and analytics doesn't care about that at all.

**Comment by JasonBarnabe** [comment]
The linked FAQ seems to say that the views **will** be recorded if I have house ads enabled (which I do).

> Most of our advertisers focus on certain regions such as North America and Europe. If a substantial amount of your site's audience is from regions outside of those, we may not have all of our traffic sold in those regions. If you have house ads enabled, you will still see ad views in our reporting there, but they will not add to your revenue.

Is this a difference between a country you have specifically blocked vs. a country you have not blocked but also have not sold any traffic for?

**Comment by davidfischer** [comment]
> The linked FAQ seems to say that the views will be recorded if I have house ads enabled (which I do).

This is correct and in fact, the fill rate metric will not be accurate if house ads are not enabled.

> Is this a difference between a country you have specifically blocked vs. a country you have not blocked but also have not sold any traffic for?

That is one way this can happen and probably the most common one. However, very small countries can have somewhat inaccurate results too just due to numbers. There could literally be only 1-2 requests and those perhaps weren't filled for a number of reasons.

**Comment by JasonBarnabe** [comment]
As a publisher, there a few pain points going on here.

Some traffic (like from China) is being completely ignored. I would expect this be reflected in stats, if not by "Views" but by some other stat that counts how many times the page with the Ethical Ads JS has been loaded, regardless of what you think of that traffic. If I could see this kind of information, I could make better decisions on where to send my traffic. Maybe I would serve up a different ad network for countries with significant traffic that you don't sell for. I need to use a separate tool like Analytics to know this information.

How the stats are calculated is not intuitive to me and not defined in the UI. I would expect "Views" to be the number of times on my pages with the Ethical Ads JS on it was viewed (regardless of whether the ad served was paid or unpaid, or if it's from China or blocked for another reason). I would expect that "Fill rate" would be paid ad requests divided by what I think "Views" are. I would expect "eCPM" to be revenue divided by every thousand "Views". I don't know if these are "standard" interpretations in the industry, but it's what I thought these things meant, and there was nothing in the UI or in documentation that I've found that would lead me to believe otherwise. And again this affects my decision making, because the reports are telling me that a placement is earning $1 eCPM, and so I think if I send another 1000 requests of my particular mix of traffic to Ethical Ads I will get $1, but really that's not true, because that stat is really saying it had to be 1000 requests-worth of traffic that Ethical Ads isn't going to ignore, and for my traffic, this is a very significant difference.

Finally, the behaviour the documentation describes does not match the actual behaviour. The FAQ says traffic from regions where you have no traffic sold will show house ads and count as such in stats. It also says house ads count as views. You have no traffic sold in China, so it should show house ads, count as house ads in the stats, and also be counted as a view. I have to file this issue in GitHub to find out that's not true.

My site is multi-language and 70% of its traffic is from China. I know that using Ethical Ads is not going to monetize this traffic, but I really need to understand what's happening and not have things completely skewed by this fact.

**Comment by davidfischer** [comment]
I will attempt to do a better job defining terms. However a "view" on a paid ad is something that an advertiser was billed for. It doesn't mean the JS was loaded or anything else. Lots of times ads are loaded but we cannot bill an advertiser for it.

> And again this affects my decision making, because the reports are telling me that a placement is earning $1 eCPM, and so I think if I send another 1000 requests of my particular mix of traffic to Ethical Ads I will get $1, but really that's not true

This is correct. Views are billed differently based on where the request comes from. Our [advertiser calculator](https://www.ethicalads.io/advertisers/calculator/) and [pricing](https://www.ethicalads.io/advertisers/pricing/) is the way we bill advertisers and what publisher earn is a percentage of. Our [publisher revenue calculator](https://www.ethicalads.io/publishers/calculator/) tries to make this clear.

> Finally, the behaviour the documentation describes does not match the actual behaviour. The FAQ says traffic from regions where you have no traffic sold will show house ads and count as such in stats.

This is generally true but there are a few regions where it isn't.

> My site is multi-language and 70% of its traffic is from China. 

Multi-language is not a problem. However for such a China heavy site, you would be better served for that traffic with another network. That is not something we can currently monetize.

**Comment by davidfischer** [comment]
I will be adding these terms to the reports themselves and have a central definition in the publisher dashboard. That won't be live until the new year. However, I think a lot of the misconception is that a "view" is a "pageview" which it is not. For us, a view is an ad view. Ad views can be paid or unpaid. If a paid ad is viewed, an advertiser will be paying for it and a publisher will be compensated. However, many times we deliver an ad and it isn't viewed (eg. reasons outlined [here](https://www.ethicalads.io/publishers/faq/#analytics-shows-more-pageviews-than-youre-showing-ad-views-why)) or we can't deliver a paid ad for a variety of reasons.

As I mentioned in [the other issue](https://github.com/readthedocs/ethical-ad-server/issues/960#issuecomment-2557526996), there are some regions where we don't even field requests at all generally because it isn't cost effective to do so. These regions won't show up in the report at all.
